name: Build java Class

on:
  push:
    branches:
  pull_request:
    branches:

jobs:
  Buildjava:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
         distribution: 'microsoft'
         java-version: '21'
    - run: |
            javac ./Server.java
            java ./Server
    - uses: actions/upload-artifact@v4
      with:
          name: ServerSomthing
          compression-level: 0
          path: |  
                 Server.class
                 ServerSomthing.class
                 Story.class
